import Home3Team from "@/components/Team/Home3Team";
import About3 from "@/components/about/About3";
import About4 from "@/components/about/About4";
import About5 from "@/components/about/About5";
import Bannder5 from "@/components/bannner/Bannder5";
import Banner3 from "@/components/bannner/Banner3";
import Banner4 from "@/components/bannner/Banner4";
import Banner6 from "@/components/bannner/Banner6";
import Home3Blog from "@/components/blog/Home3Blog";
import Preloader from "@/components/common/Preloader";
import Home3Contact from "@/components/contact/Home3Contact";
import Footer2 from "@/components/footer/Footer2";
import Footer3 from "@/components/footer/Footer3";
import Header from "@/components/header/Header";
import Header3 from "@/components/header/Header3";
import HeaderMain from "@/components/header/HeaderMain";
import Partnar4 from "@/components/partner/Partnar4";
import Partnar6 from "@/components/partner/Partnar6";
import Partner3 from "@/components/partner/Partner3";
import Partner5 from "@/components/partner/Partner5";
import PricingPlan3 from "@/components/pricingplan/PricingPlan3";
import Solution3 from "@/components/solutions/Solution3";
import SuccessStory3 from "@/components/successStorys/SuccessStory3";
import Testimonial3 from "@/components/testimonial/Testimonial3";
import useBodyClass from "@/hooks/useBodyClass";
import Head from "next/head";
import AboutPage from "./about";
import Home4Contact from "@/components/contact/Home4Contact";

export default function Home() {
  useBodyClass("home-dark2");

  return (
    <>
      <Head>
        <title>
          Async Solutions LLC
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="..\favicon.ico" />
        <script
          src='//fw-cdn.com/11660372/4305969.js'
          chat='true'>
        </script>
      </Head>

      <HeaderMain />
      <Banner6 />
      <Partnar6 />

      <Solution3 />

      <Partner3 />

      <About3 />
      {/* <SuccessStory3 /> */}
      <Testimonial3 />
      <Home3Team />
      <Home4Contact />

      {/* <Home3Blog /> */}
      <Footer2 />
    </>
  );
}
